// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZxeIR1wivwLG5KuRf1RRsbaqjpVXW_vk',
    appId: '1:365176907982:web:69d54d88811be38783c89f',
    messagingSenderId: '365176907982',
    projectId: 'booking-app-prod-aa468',
    authDomain: 'booking-app-prod-aa468.firebaseapp.com',
    storageBucket: 'booking-app-prod-aa468.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqwLFi7t87Z0y59fjfsfYOtB1VAwGw-w',
    appId: '1:365176907982:android:5b2cfaea30c30bd983c89f',
    messagingSenderId: '365176907982',
    projectId: 'booking-app-prod-aa468',
    storageBucket: 'booking-app-prod-aa468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl4uqkuSWlMBDr5F1BJTmHkavp_5XGjYk',
    appId: '1:365176907982:ios:a17e55e66f02160b83c89f',
    messagingSenderId: '365176907982',
    projectId: 'booking-app-prod-aa468',
    storageBucket: 'booking-app-prod-aa468.firebasestorage.app',
    iosClientId: '365176907982-6ofjudg02540q9sfjp0opmav3v3bmvue.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZxeIR1wivwLG5KuRf1RRsbaqjpVXW_vk',
    appId: '1:365176907982:web:547312651f31085d83c89f',
    messagingSenderId: '365176907982',
    projectId: 'booking-app-prod-aa468',
    authDomain: 'booking-app-prod-aa468.firebaseapp.com',
    storageBucket: 'booking-app-prod-aa468.firebasestorage.app',
  );
}
